[package]
name = "auto-registry"
version = "0.0.4"
edition = "2021"

[lib]
proc-macro = true
doctest = false

[dependencies]
proc-macro2 = { version = "1.0" }
quote = "1.0"
syn = { version = "1.0", features = [ "full" ] }
